name: Learn Web Server In C++
on:
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Debug


jobs:
  build-the-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Project
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Show Result
        run: |
          ${{github.workspace}}/bin/tests
          cat ${{github.workspace}}/build/log.txt

      

  