name: Learn Web Server In C++
on:
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Debug


jobs:
  build-the-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install Boost Lib
        run: sudo apt install libboost-all-dev -y
      
      - name: Install YAML-CPP LIB
        run: |
            git clone https://github.com/jbeder/yaml-cpp.git
            cd yaml-cpp
            mkdir build
            cd build
            cmake ..
            sudo make install
      - name: Install Ragel
        run: sudo apt install ragel -y
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build Project
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      # - name: Show Result
      #   run: |
      #     ${{github.workspace}}/bin/tests
      #     ls ${{github.workspace}}/build
      #     ls ${{github.workspace}}/bin

      

  